### ISSUE TITLE
Getting issue while installing app at production mode

### ISSUE THREAD

**Issue by yedladinesh** [kinngh/shopify-node-express-mongodb-app#129] opened 2024-05-16 10:29 UTC
Hi @kinngh 

Recently, I submitted an app to the Shopify app store, and the Shopify support team emailed me, stating that they're encountering an issue while installing the app. Upon investigation, I found that I am facing the same issue. Let me explain:

1. The first time I installed the app using the URL, it installed successfully and worked perfectly, 
like this: https://abc.com/api/auth?shop=xyz.myshopify.com.
2. After I uninstalled the app.
3. When I reinstalled the app from the Shopify "Uninstall" tab, I encountered the issue: "admin.shopify.com redirected you too many times."

**Please also review the attached video for a better understanding:** https://drive.google.com/file/d/1k2Yraebe27FmrN1YWBFfpjajwoqTerwR/view?usp=drive_link

![image](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/52268507/ddcbbb17-8bac-4200-924a-a5c21b9d65c1)

**Here's the error log for further investigation.**

`[shopify-api/ERROR] Could not find OAuth cookie | {shop: dev-upsell2.myshopify.com}
 ---> Error at /api/auth/tokens CookieNotFound [Error]: Cannot complete OAuth process. Could not find an OAuth cookie for shop url: dev-upsell2.myshopify.com
     at Object.callback (/var/www/dev-upsell/node_modules/@shopify/shopify-api/lib/auth/oauth/oauth.js:99:19)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async file:///var/www/dev-upsell/server/middleware/auth.js:57:32
`

Please help me out. I have been using this package for a long time, and I have never faced this issue before. I appreciate your insight.

Thanks

**Comment by kinngh** [comment] 2024-05-16 11:24
See if either of these gists I wrote a good while ago solve your issue. MAKE SURE YOU SAVE YOUR CHANGES BEFORE RUNNING THE SCRIPTS BECAUSE IT CHANGES A BUNCH OF CORE PACKAGES.

1. https://gist.github.com/kinngh/995a64372e8d698c38ca4aaef61e2edc
2. https://gist.github.com/kinngh/ab36102f4c1f2bdd9a56729253af222b

If it doesn't work, lmk, I'll migrate the entire thing over to managed install and write a guide so the older OAuth issues are completely taken care of

**Comment by yedladinesh** [comment] 2024-05-18 05:50
Hi @kinngh 


Thanks for sharing the patch; it really helps me a lot. The patch is running perfectly. However, I think the code below didn't work. So, I manually changed "lax" to "none," and now it's working fine :)


`const domainEntry = "domain: `.${config.hostName}`,";
  let result;

  if (data.includes(domainEntry)) {
    // If domain entry already exists, replace it
    result = data.replace(new RegExp(domainEntry, "g"), domainEntry);
  } else {
    // If domain entry doesn't exist, add it
    const regex = /(sameSite: 'lax',\n\s+secure: true,)/g;
    result = data.replace(regex, `$1\n${domainEntry}`);
  }`
  
  
  Thanks for your support and appreciate your help

**Comment by yedladinesh** [comment] 2024-05-24 10:35
Hi @kinngh 

I am facing another issue related to cookies. Here's the error message I received from the Shopify support team:

**Your embedded app must use session tokens and not rely on 3rd party cookies to function properly. Your embedded app must not use local storage. Your app must function in incognito mode in Chrome.**

![1image_2024_05_24T06_26_35_027Z](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/52268507/8fb21460-8d44-420d-91f5-76bea3ddd111)

Additionally, please check the attached video.

https://drive.google.com/file/d/1PdLEs_0UPnyDnI5h9-lR61yc_x5H--BE/view?usp=sharing


I appreciate your insight.

Thanks

**Comment by kinngh** [comment] 2024-05-24 12:21
Ok what version is your `@shopify/shopify-api`? Looks like an older version. Also, This could, highly likely, just be the app reviewer being dumb. A lot of these cases happen regularly.

**Comment by kinngh** [comment] 2024-05-24 20:19
upgrade App Bridge to App Bridge CDN, uninstall app bridge packages and see the repo in it's current state to understand how the new CDN works. I _suspect_ that could be the problem since it's also taking you to `*.myshopify.com` domain instead of `admin.shopify.com/store/*`. Also lowkey surprised why you don't have it upgraded already

**Comment by yedladinesh** [comment] 2024-05-27 09:22
I tried to upgrade the whole package to a new version and I am using `"@shopify/shopify-api": "^10.0.0"` along with the App Bridge CDN. However, I am still facing the same issue. Please check the attachment below.

Additionally, for further clarification, I suggest you try setup the latest package on the server end and attempt the installation in an incognito window.

![image_2024_05_27T09_14_41_256Z](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/52268507/3a2a1880-7beb-4c4a-9582-85a464065024)

**Comment by kinngh** [comment] 2024-05-27 09:33
All of my boilerplates are what I use in production - this is not a throw away open source project that I maintain out of kindness, this is what I personally use in production and open sourced it for everyone to use.

That said, 4 days ago I went through app review with no problems using this exact boilerplate, so please double check your project on what's happening - it's either a package or some of your code that's causing the issue because if it was an actual problem with the base boilerplate, I would have multiple people reporting problems with it and I would have a solution for it, like what I had with the auth.

Moreover, the screenshot alone is of absolutely 0 help - I don't have any error logs, server setup, etc. _I do not have the time to sit around and debug an issue that cannot be reliably reproduced just for one project_.

Closing this issue.

**Comment by kinngh** [comment] 2024-05-27 09:42
Also, just so I don't hear from you that I didn't pull the latest commit and try it out, here's a screen cast of installing a freshly pulled, freshly created boilerplate app in Safari's Private mode, the absolute worst browser to try it out on.

https://youtu.be/MKrp7GaiW7M

**Closed by kinngh** 2024-05-27 09:42 UTC
Labels: bug, OEM Bug

**Comment by yedladinesh** [comment] 2024-05-27 09:54
Thanks for you efforts and tried it out. Could you please try it out at the chrome browser and make sure disable the third-party cookies (Private window).

Also, I freshly installed the package at live server.

![image_2024_05_27T09_50_59_044Z](https://github.com/kinngh/shopify-node-express-mongodb-app/assets/52268507/cce1166e-9d01-480b-ad17-63f6a456de12)

**Comment by kinngh** [comment] 2024-05-27 11:50
I did try it out with Chrome, Safari, Firefox and Arc, and it all worked just fine, and only uploaded the Safari one, since if it works on Safari, it works everywhere.

**Comment by kinngh** [comment] 2024-06-03 09:54
Tracking this in #132 . THAT is how you write a proper error log, and not just post a screenshot with no logging whatsoever.

**Comment by kinngh** [comment] 2024-06-03 12:31
Fixed in [c747c](https://github.com/kinngh/shopify-node-express-mongodb-app/commit/c0b2d63eedc4eee156d29572d57bf6e0ba2c747c)
